// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zV9JJjOtsvLU89jEGLE8uslmz3FAFoE',
    appId: '1:40151506245:web:d8566c730771528c1e322c',
    messagingSenderId: '40151506245',
    projectId: 'task-management-6ed3f',
    authDomain: 'task-management-6ed3f.firebaseapp.com',
    storageBucket: 'task-management-6ed3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWtFOD9OaaqrGCbDh94sVfKV7aFuhzWtE',
    appId: '1:40151506245:android:36c63cb4fbbd36d51e322c',
    messagingSenderId: '40151506245',
    projectId: 'task-management-6ed3f',
    storageBucket: 'task-management-6ed3f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC59qL8wOX2KjBswzP83yUMYd3Yp8Ta-LM',
    appId: '1:40151506245:ios:88f44785262e276c1e322c',
    messagingSenderId: '40151506245',
    projectId: 'task-management-6ed3f',
    storageBucket: 'task-management-6ed3f.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC59qL8wOX2KjBswzP83yUMYd3Yp8Ta-LM',
    appId: '1:40151506245:ios:88f44785262e276c1e322c',
    messagingSenderId: '40151506245',
    projectId: 'task-management-6ed3f',
    storageBucket: 'task-management-6ed3f.firebasestorage.app',
    iosBundleId: 'com.example.taskManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zV9JJjOtsvLU89jEGLE8uslmz3FAFoE',
    appId: '1:40151506245:web:c64de46888fae7da1e322c',
    messagingSenderId: '40151506245',
    projectId: 'task-management-6ed3f',
    authDomain: 'task-management-6ed3f.firebaseapp.com',
    storageBucket: 'task-management-6ed3f.firebasestorage.app',
  );
}
